---
name: Linting
on:
  push: null
permissions:
  contents: read
jobs:
  linting:
    uses: aura-portal/.github/.github/workflows/linting.yaml@main
    permissions:
      contents: read
      packages: read
      statuses: write
      checks: write
