---
name: Release
on:
  release:
    types:
      - published
jobs:
  linting:
    uses: aura-portal/.github/.github/workflows/linting.yaml@main
  versions:
    uses: aura-portal/.github/.github/workflows/versions.yaml@main
    needs: linting
    with:
      tag: ${{ github.ref_name }}
  docker-release:
    uses: aura-portal/.github/.github/workflows/docker-release.yaml@main
    needs: versions
    with:
      major: ${{ needs.versions.outputs.major }}
      minor: ${{ needs.versions.outputs.minor }}
      patch: ${{ needs.versions.outputs.patch }}
